version: '3.7'
services:
  consul:
    image: consul:1.3.0
    command: consul agent -dev -recursor=8.8.8.8 -client 0.0.0.0
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS
    ports:
      - "8500:8500"
      - "53:8600/udp"
  registrator:
    command: -internal consul://consul:8500
    image: gliderlabs/registrator:v7
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    links:
      - consul
  customer:
    build: ../microservice-consuldns-demo/microservice-consuldns-demo-customer
    environment:
    - SERVICE_NAME=msconsuldns-customer
  catalog:
    build: ../microservice-consuldns-demo/microservice-consuldns-demo-catalog
    environment:
    - SERVICE_NAME=msconsuldns-catalog
  order:
    build: ../microservice-consuldns-demo/microservice-consuldns-demo-order
    dns: ${CONSUL_HOST}
    environment:
    - SERVICE_NAME=msconsuldns-order
  apache:
    build: apache
    links:
     - consul
    depends_on:
     - consul
    ports:
     - "8080:80"